name: Deploy Azure Monitor POC Modules

on:
  workflow_dispatch:

jobs:
  associate-dcr:
    name: Associate DCR with VM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./terraform/dcr_association
      env:
        TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/dcr_association
      env:
        TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform/dcr_association
      env:
        TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      run: terraform apply -auto-approve
